version: 2.0.1.{build}

image: Visual Studio 2017

configuration: Release
platform: Any CPU

before_build:
  - dotnet restore

build_script:
  - dotnet build

after_build:
  - dotnet pack src\D2L.Services.Core.Exceptions\D2L.Services.Core.Exceptions.csproj

test_script:
  - dotnet test test\D2L.Services.Core.Exceptions.UnitTests\D2L.Services.Core.Exceptions.UnitTests.csproj

dotnet_csproj:
  patch: true
  file: src\**\*.csproj
  version: '{version}'

artifacts:
  - path: src\**\*.nupkg
    name: NuGet

deploy:
  - provider: NuGet
    api_key:
      # D2L.Services.Core.Exceptions (Expires: 2019-12-03)
      secure: WMUAm6usecFZkPPlSyWdbiMoyrw+SmAZhcT36+IEN+H3RCna+XchlPBTmZJLYs5W
    on:
      APPVEYOR_REPO_TAG: true
